// Tier-2 Rising home content — human-story copy (from the v1 build), Navy/Orange brand.

export const story = {
  title: 'Why We Built the Room',
  body:
    'There are founders in Tier 2 cities as good as anyone in Chennai or Bangalore — working just as hard, with an idea just as good. What they don’t have is easy access to a room full of investors, the thing a metro founder barely thinks about. The talent was never the problem. The access was. We’re closing that gap in a single day.',
}

export const scores = [
  { n: '10', label: 'startups coached to funding-readiness' },
  { n: '3', label: 'pitch live on the main stage' },
  { n: '5', label: 'initiatives unveiled to keep it going' },
  { n: '1', label: 'day · every door open' },
]

export type Zone = { title: string; sub: string; accent: 'accent' | 'purple' | 'cyan' | 'gold' | 'green' }
export const zones: Zone[] = [
  { title: 'Government Grants', sub: 'Scheme officers who can say yes on the day — not six forms later.', accent: 'accent' },
  { title: 'New-Age Investors', sub: 'Angels, syndicates and micro-VCs actually looking in Tier-2.', accent: 'gold' },
  { title: 'Banking & Credit', sub: 'The bank people who sign off the loan, at a desk you can walk up to.', accent: 'cyan' },
  { title: 'Startup Exhibit', sub: 'The ten startups, up close — see what they’ve actually built.', accent: 'purple' },
  { title: "Deal & Investors' Corner", sub: 'A quieter corner for the conversations that matter.', accent: 'green' },
]

// Programme cards — real free-license imagery + the "climb / the day" copy.
export type WhatCard = { label: string; img: string; desc: string }
export const whatGoesOn: WhatCard[] = [
  {
    label: 'Founder Bootcamp',
    img: '/happens/bootcamp.jpg',
    desc: 'Ten Tier-2 startups coached on the pitch, cap table, data room and the questions investors actually ask.',
  },
  {
    label: 'Diligence & Selection',
    img: '/happens/diligence.jpg',
    desc: 'A panel sits with each startup and picks the three that are ready to take the stage.',
  },
  {
    label: 'The Live Finale',
    img: '/happens/finale.jpg',
    desc: 'Three startups pitch to a room that can say yes. The other seven are recognised on stage too.',
  },
  {
    label: 'Growth Zones, All Day',
    img: '/happens/zones.jpg',
    desc: 'Grants, investors, banking and the deal corner — open all day. Walk up anytime.',
  },
  {
    label: 'Startup Exhibit',
    img: '/happens/exhibit.jpg',
    desc: 'The ten startups up close — see what they’ve actually built, not just a slide.',
  },
  {
    label: 'Every Door Open',
    img: '/happens/entry.jpg',
    desc: 'Investors, scheme officers, bank heads and mentors — under one roof in Erode, no borrowed contact needed.',
  },
]

/*
 * THE STAGE — the announced speakers, in the order the client's artwork runs them.
 *
 * THIS REPLACED A LIST OF ARCHETYPES. It used to read 'Angels', 'Micro-VC Leads',
 * 'Founders Who Raised', 'Announced Soon' — written while the lineup was still being
 * confirmed, and never rendered by anything: no component ever imported it. Placeholder
 * copy that no page shows is worse than none, because the day real names arrive somebody
 * has to work out whether the old list was a promise. These are names.
 *
 * EVERY ENTRY IS A REAL PERSON AND A REAL COMPANY, transcribed from the client's
 * announcement cards. Spelling, honorifics and the exact wording of a title are as
 * supplied — "Mr." / "Ms." are part of the name here, and a role is not to be tidied,
 * shortened or corrected from memory. Change one only against something the client has
 * sent, the same rule the launch credits below are under.
 */
export type Speaker = {
  /** As printed on the card, honorific included. */
  name: string
  /**
   * Everything under the name. ' · ' separates two affiliations — Speakers.tsx does not
   * parse it, it is simply the separator the rest of the site uses for the same job.
   */
  role: string
  /** 3:4 portrait in /public/speakers. Generated by scripts/speakers.py — read it first. */
  photo: string
  /**
   * The chip above the name. Per speaker rather than a constant, because the lineup will
   * not stay flat: a chief guest, a keynote or a jury member is a different thing from a
   * guest speaker, and the day one is added should not be the day this becomes a prop.
   */
  badge: string
}

export const speakersIntro =
  "Founders and ecosystem builders who have scaled from Tamil Nadu's Tier-2 cities, on stage at Fortune City, Erode."

export const speakers: Speaker[] = [
  {
    name: 'Mr. C K Kumaravel',
    role: 'CEO & Co-Founder, Naturals',
    photo: '/speakers/kumaravel-v1.jpg',
    badge: 'Guest Speaker',
  },
  {
    name: 'Mr. Harish Venkatesh',
    role: 'Founder & CEO, Become',
    photo: '/speakers/harish-v1.jpg',
    badge: 'Guest Speaker',
  },
  {
    name: 'Ms. Archana Stalin',
    role: 'Founder, myHarvest Farms',
    photo: '/speakers/archana-v1.jpg',
    badge: 'Guest Speaker',
  },
  {
    name: 'Mr. Sathishkumar P',
    role: 'Head, Learning & Development, i-exceed Technology Solutions · Organizer, GDG Salem & AI Salem',
    photo: '/speakers/sathish-v1.jpg',
    badge: 'Guest Speaker',
  },
]

// Real partner logos + their roles.
// `url` is optional: a partner with one becomes a link to their site, a partner
// without one stays a plain card. Don't invent a URL to fill the gap — a dead or
// guessed link is worse than no link.
/*
 * THE LAUNCH PHOTO, shown beside the hero panel.
 *
 * The summit was unveiled on stage at Aakam – Startup Connect, and the photograph is the
 * proof: a government minister and the chairman of StartupTN holding the poster, with two
 * district collectors present. That is a credential no amount of copy buys, which is why
 * it sits in the hero rather than in a gallery further down.
 *
 * EVERY NAME AND TITLE HERE IS A REAL PERSON'S, several of them public officials. They are
 * transcribed from the client's artwork and must be changed only against something the
 * client has signed off — not corrected from memory, and not guessed at. Honorifics
 * ("Thiru.", "I.A.S.", "Hon'ble") are part of the name as supplied and are kept verbatim.
 */
export type LaunchPerson = { name: string; role: string }
export type LaunchGroup = { label: string; people: LaunchPerson[] }

export const launch = {
  /*
   * Two widths, srcset'd. next.config.mjs turns the image optimizer OFF (we serve plain
   * <img> from a small Node box), so nothing generates responsive sources for us — the
   * alternative is shipping a 1600px file to a phone showing it 340px wide.
   * Both are generated from the client's unveiling graphic by scripts/launch-photo.py.
   */
  photo: {
    src: '/happens/launch-unveiling-v2-1600.jpg',
    srcSet: '/happens/launch-unveiling-v2-900.jpg 900w, /happens/launch-unveiling-v2-1600.jpg 1600w',
    width: 1600,
    height: 900,
    /*
     * Describes the EVENT, not the pixels. This image is evidence that the launch happened
     * and who was at it, so a reader who cannot see it needs the same fact the sighted
     * reader takes from it — the caption below then adds the names.
     */
    alt: 'Tier2Rising – Startup Summit Unveiling: the summit poster being unveiled on stage at Aakam – Startup Connect.',
  },
  caption: 'Officially launched at Aakam – Startup Connect',
  date: '11 September 2026',
  /*
   * The same date for the badge burned into the corner of the photo on mobile, where the
   * caption line has no room to carry it. Spelled out rather than sliced off `date`, for
   * the reason site.datesCompact exists: deriving it with a string replace does not fail
   * when the month changes, it silently does nothing.
   */
  dateShort: '11 Sep 2026',
  groups: [
    {
      label: 'Unveiled by',
      people: [
        { name: 'Dr. K.G. Arunraj', role: 'Hon’ble Minister for Health and Family Welfare' },
        { name: 'Mr. Singai G. Ramachandran', role: 'Chairman, StartupTN' },
      ],
    },
    {
      label: 'Along with',
      people: [
        { name: 'Thiru. K. Elambahavath, I.A.S.', role: 'District Collector, Salem' },
        { name: 'Thiru. L. Madhubalan, I.A.S.', role: 'District Collector, Namakkal' },
      ],
    },
  ] as LaunchGroup[],
}

export type Partner = { label: string; logo: string; name: string; url?: string }
export const partners: Partner[] = [
  { label: 'Event Founder & Principal Organiser', logo: '/logos/nammaoffice-v3.png', name: 'NammaOffice', url: 'https://nammaoffice.com/' },
  /*
   * Curd Rice replaced 3iOS as event co-founder in October 2026.
   *
   * The asset is derived, not the file the client supplied: that one is RGB on a white
   * ground, which would have shown as a near-white square proud of the card's rounded
   * corners and hairline border. See scripts/curdrice-transparent.py for why the ground was
   * removed by COLOUR KEY here and by flood fill on StartupTN below — the two pieces of
   * artwork need opposite rules, and each rule ruins the other file.
   *
   * NO `url`. One was never supplied, and a guessed or dead link on a partner credit is
   * worse than a card that simply does not click — the same rule the TealOrca note above
   * came out of. Add it the moment the client sends one.
   */
  { label: 'Event Co-Founder & Strategic Partner', logo: '/logos/curdrice-v1.png', name: 'Curd Rice' },
  { label: 'Pitch & Media Partner', logo: '/logos/startupsingam.png', name: 'Startup Singam', url: 'https://www.startupsingam.com/' },
  // tealorca.com, not the .in the brief originally gave. Both resolve, but .in
  // redirects to /home.php while .com serves the site at its root — verified 200 over
  // https on both. https, not http: an http link hands the visitor a "Not secure"
  // warning on the way to our own technology partner.
  { label: 'Technology Partner', logo: '/logos/tealorca.png', name: 'TealOrca', url: 'https://tealorca.com/' },
  /*
   * StartupTN — the Tamil Nadu government's startup mission.
   *
   * The asset is derived, not the file the client supplied: that one is RGB on a #F7F7F7
   * ground, which would have shown as a faint grey rectangle on the white card while every
   * other logo here sits on nothing. See scripts/startuptn-transparent.py for why the
   * white was removed by flood fill rather than by colour key — the Tamil Nadu emblem has
   * a white disc a colour key punches straight out.
   *
   * NOTE: StartupTN is also listed by name, without a logo, under "Government Enablement"
   * in govPartners below. Both are true — it is a government body and an ecosystem partner
   * — but if the client wants it in one place only, this card is the one to keep.
   *
   * https://startuptn.in/ verified 200 over https.
   */
  { label: 'Ecosystem Partner', logo: '/logos/startuptn-v1.png', name: 'StartupTN', url: 'https://startuptn.in/' },
]

export type GovPartner = { name: string; logo?: string }
export type GovGroup = { group: string; items: GovPartner[] }
export const govPartners: GovGroup[] = [
  {
    group: 'Government Enablement',
    items: [
      { name: 'StartupTN' },
      { name: 'TANSEED' },
      { name: 'TIIC', logo: '/logos/tiic.png' },
      { name: 'DIC' },
      { name: 'MSME', logo: '/logos/msme.png' },
    ],
  },
  {
    group: 'Banking & Credit',
    items: [
      { name: 'SIDBI', logo: '/logos/sidbi.png' },
      { name: 'MUDRA', logo: '/logos/mudra.png' },
      { name: 'CGTMSE' },
    ],
  },
  {
    group: 'Ecosystem & Community',
    items: [{ name: 'Kongu Business Bodies' }, { name: 'Startup Singam', logo: '/logos/startupsingam.png' }],
  },
]

// Belief lines — rotating statements.
export const statements = [
  { text: 'Great businesses should not be limited by geography.', author: 'The Tier-2 Rising belief' },
  { text: 'The talent was never the problem. The access was.', author: 'Why we built the room' },
  { text: 'One day. Every door open.', author: '21 November · Erode' },
  { text: 'Tier-2 is rising.', author: 'Coimbatore · Erode · Salem · Tiruppur · Madurai · Trichy' },
]

/**
 * The Vision / Mission section, between the countdown and the story.
 *
 * Copy is supplied verbatim by the client. Note "programs" — the rest of the site uses
 * British spelling ("Founder Programme"), so this one word is inconsistent on purpose
 * rather than by oversight: it is their wording, and changing supplied copy silently is
 * how a review turns into an argument about what was approved.
 */
export type VisionPillar = {
  /** Orange pill above the statement. */
  tag: string
  /** The statement itself — the largest type in the section. */
  statement: string
  /** Small caps label on the card below. */
  cardLabel: string
  cardBody: string
}

export const visionPillars: VisionPillar[] = [
  {
    tag: 'Vision',
    statement: 'Tier-2 cities as strong startup growth hubs.',
    cardLabel: 'What it is',
    cardBody:
      'An ongoing initiative connecting Tier-2 founders with the funding, mentorship, and networks they need to grow — built through year-round programs, not a one-off event.',
  },
  {
    tag: 'Mission',
    statement: 'Connect founders to investors, banks, mentors & enablers.',
    cardLabel: 'Why now',
    cardBody:
      'Tier-2 cities have talent, ideas and a strong business culture — but startups here still lack equal access to funding, mentors, government schemes, bank support and investor networks.',
  },
]
